name: intranet_maispet
version: 1.0.0+1
description: Intranet +PET

publish_to: 'none'



environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.4
  dropdown_button2: ^2.3.4
  excel: ^2.0.1
  spreadsheet_decoder: ^2.0.0
  pdf: any
  printing: ^5.5.0
  hexcolor: ^2.0.4
  flutter_form_builder: ^9.1.0
  shared_preferences: ^2.2.1
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.4.5
  cloud_firestore: ^4.9.1
  firebase: ^9.0.0
  google_fonts:
  animated_background:
  form_builder_image_picker: ^4.0.0
  image_picker: ^0.8.9
  universal_io: ^2.2.2
  universal_html: ^2.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  build_web_compilers: any

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/files/
